version: "3.7"
services:

  discord:
    image: formulabun/discord:0.1.1
    build:
      dockerfile: Dockerfile.discord
    environment:
      TOKEN: "${DISCORD_TOKEN}"
      APPLICATIONID: "${DISCORD_APPLICATION}"
      TESTGUILD: "${DISCORD_TESTGUILD}"

  translator:
    image: formulabun/translator:0.1.0
    build:
      dockerfile: Dockerfile.translator
    ports:
      - 5092:5092
    environment:
      TARGET: "${IP}:${SRB2KART_MAIN_PORT}"
