version: "3.7"
services:

  discord:
    image: formulabun/discord:alpha
    build:
      dockerfile: Dockerfile.discord
    environment:
      TOKEN: "${DISCORD_TOKEN}"

  translator:
    image: formulabun/translator:alpha
    build:
      dockerfile: Dockerfile.translator
    ports:
      - 5092:5092
    environment:
      TARGET: "${IP}:${SRB2KART_MAIN_PORT}"
