FROM golang:1.18

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

# Build script
RUN go build -v -o translator ./services/translator/service.go
CMD ["./translator"]
