version: "3.7"
services:

  discord:
    image: formulabun/discord:0.0.1
    build:
      dockerfile: Dockerfile.discord
    environment:
      TOKEN: "${DISCORD_TOKEN}"
    network_mode:
      host

  translator:
    image: formulabun/translator:0.0.1
    build:
      dockerfile: Dockerfile.translator
    ports:
      - 5092:5092
    network_mode:
      host

  db:
    image: mongo:5.0.9
    ports:
      - 27017:27017
    network_mode:
      host
    volumes:
      - database:/data/db

  scripts:
    image: formulabun/scripts
    build:
      dockerfile: Dockerfile.scripts
    stdin_open: true
    tty: true
    network_mode:
      host
    volumes:
      - files:/data/files
volumes:
  database: {}
  files: {}
