version: "3.7"
services:
  translator:
    image: gobun-translator/latest
    build:
      dockerfile: Dockerfile.translator
    ports:
      - 5129:8080
    network_mode:
      host
  db:
    image: mongo:5.0.9
    ports:
      - 27017:27017
    network_mode:
      host
    volumes:
      - database:/data/db
  scripts:
    image: gobun-scripts/latest
    build:
      dockerfile: Dockerfile.scripts
    stdin_open: true
    tty: true
    network_mode:
      host
    volumes:
      - files:/data/files
volumes:
  database: {}
  files: {}
