version: "3.7"
services:
  translator-swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 80:8080
    volumes:
      - ./services/translator:/openapi
    environment:
      SWAGGER_JSON: /openapi/api.yml
